name: navigation_drawers
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dot_navigation_bar: ^1.0.1+3
  url_launcher: ^6.0.10
  share: ^2.0.4
  flutter_svg: ^0.19.1
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
